[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Empyrean"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = [
	"--import-mode=importlib",
]
pythonpath = "api"
