"""user_add-names-and-isAdmin

Revision ID: 3a1d0b0b9397
Revises: 6ba4cbca9ddc
Create Date: 2023-04-01 08:45:41.963828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a1d0b0b9397'
down_revision = '6ba4cbca9ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('isadmin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isadmin')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
