"""Initial migration

Revision ID: 5778321bd8e0
Revises: 
Create Date: 2023-02-19 11:29:50.473292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5778321bd8e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('instrumentId', sa.Integer(), nullable=False),
    sa.Column('instrumentName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('instrumentId')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrumentID', sa.Integer(), nullable=True),
    sa.Column('statusName', sa.String(), nullable=True),
    sa.Column('statusValue', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    op.drop_table('instrument')
    # ### end Alembic commands ###
