# Sources:
# https://github.com/actions/setup-python
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Setup environment

on:
  push:
    branches: [ "main", "ci-cd" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_frontend:
    runs-on: ubuntu-latest

    strategy:
        matrix:
            # https://nodejs.org/en/about/releases/
            node-version: [18.x, 19.x]

    steps:
    - uses: actions/checkout@v3

    - name: Start Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build --if-present
